### ISSUE TITLE
Error: Evaluation Error: Error while evaluating a Function Call, The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access

### ISSUE THREAD

**Issue by Dharmender-Singh** [voxpupuli/hiera-eyaml#263]
Hi,

I am trying to use KMS with Hiera 5 but getting following error :  

"Error: Evaluation Error: Error while evaluating a Function Call, The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access."

But when I used eyaml cli for encryption ,then it's working fine for the same AWS IAM user. So I think, it's not the AWS permission. May be I am missing some configuration in hiera yaml file
Following is my hiera.yaml :  

```
version: 5
defaults:
  datadir: data
hierarchy:
  -
    lookup_key: eyaml_lookup_key
    name: "Secret data: per-node, per-datacenter, common"
    options:
      encrypt-method: KMS
      kms_key_id: KeyID
      kms_aws_region: aws region
    paths:
      - "nodes/%{trusted.certname}.yaml"
      - "%{::environment}.yaml"
      - "os/%{::osfamily}.yaml" 
```

Thanks
