### ISSUE TITLE
Allow Hash keys as Array

### ISSUE THREAD

**Issue by tuxmea** [voxpupuli/hiera-eyaml#337]
I want to set a hash key to an array:

```yaml
stdlib::manage::create_resources:
  package:
    ['htop', 'strace', 'less']:
      ensure: installed
```

EYaml produces the following error:

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Value for key 'stdlib::manage::create_resources', returned from lookup_key function 'eyaml_lookup_key', when using location '/etc/puppetlabs/code/environments/production/data/common.yaml', has wrong type, expects Puppet::LookupValue, got Hash[String, Hash[Array[Enum['htop', 'less', 'strace'], 3, 3], Hash[String, String, 1, 1], 1, 1], 1, 1] on node puppet5.ma.betadots.training
```
